# Generated by Django 3.2.1 on 2021-07-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_categoria', models.CharField(max_length=255, verbose_name='Ingrese la categoria del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Ingrese el nombre del producto')),
                ('imagen', models.ImageField(max_length=255, upload_to='', verbose_name='Suba la imagen del producto')),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario1', models.CharField(max_length=255, verbose_name='Ingrese el nombre del usuario')),
                ('total_carrito', models.CharField(max_length=20)),
                ('lista_productos', models.ManyToManyField(help_text='Seleccione lista de productos', to='app.Producto')),
            ],
        ),
    ]
